from django.urls import path
from .views import (
    home_page,
    register_page,
    MyLoginView,
    logout_user,
    profile_page,
    profile_view,
    edit_profile_view,
    follower_list_view,
    following_list_view,
    create_post_view,
    submit_report_view,
    feed_page,
    follow_user_view,
    post_detail_view,
    edit_post_view,
    delete_post_view,
    like_post_view,
    comment_post_view,
    notifications_page,
    explore_page,
    search_view,
    admin_stats_view,
    report_list_view,
    message_inbox_view,
    send_message_view,
    conversation_view,
    user_profile_view
)

urlpatterns = [
    path('', home_page, name='home'),
    path('register/', register_page, name='register'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/edit/', edit_profile_view, name='edit-profile'),
    path('profile/<int:pk>/', profile_view, name='profile'),
    path('profile/<str:username>/', user_profile_view, name='user-profile'),
    path('profile/<int:user_id>/followers/', follower_list_view, name='follower-list'),
    path('profile/<int:user_id>/following/', following_list_view, name='following-list'),
    path('feed/', feed_page, name='feed'),
    path('follow/', follow_user_view, name='follow-user'),
    path('post/<int:post_id>/', post_detail_view, name='post-detail'),
    path('post/<int:post_id>/edit/', edit_post_view, name='edit-post'),
    path('post/<int:post_id>/delete/', delete_post_view, name='delete-post'),
    path('report/post/<int:post_id>/', submit_report_view, name='submit-report'),
    path('create/', create_post_view, name='create-post'),
    path('like/', like_post_view, name='like-post'),
    path('comment/', comment_post_view, name='comment-post'),
    path('notifications/', notifications_page, name='notifications'),
    path('explore/', explore_page, name='explore'),
    path('search/', search_view, name='search'),
    path('admin/stats/', admin_stats_view, name='admin-stats'),
    path('admin/reports/', report_list_view, name='admin-reports'),
    path('messages/', message_inbox_view, name='message-inbox'),
    path('messages/send/', send_message_view, name='send-message'),
    path('messages/chat/<int:user_id>/', conversation_view, name='conversation'),

]
